### ISSUE TITLE
 Mixlib::ShellOut::ShellCommandFailed

### ISSUE THREAD

**Issue by deeco** [test-kitchen/kitchen-dokken#161]
git[/home/notroot/kitchen-dokken] action sync

    ================================================================================
    Error executing action `sync` on resource 'git[/home/notroot/kitchen-dokken]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '128'
    ---- Begin output of git clone "/opt/kitchen-dokken/.git" "/home/notroot/kitchen-dokken" ----
    STDOUT:
    STDERR: fatal: repository '/opt/kitchen-dokken/.git' does not exist
    ---- End output of git clone "/opt/kitchen-dokken/.git" "/home/notroot/kitchen-dokken" ----
    Ran git clone "/opt/kitchen-dokken/.git" "/home/notroot/kitchen-dokken" returned 128

    Resource Declaration:
    ---------------------
    # In /opt/kitchen/cache/cookbooks/dokken_test/recipes/default.rb

     33: git '/home/notroot/kitchen-dokken' do
     34:   repository '/opt/kitchen-dokken/.git'
     35:   revision node['dokken_test']['revision']
     36:   user 'notroot'
     37:   action :sync
     38: end
     39:

**Comment by marcparadise** [comment]
Given the age, and the common flow (normal startup of kitchen-dokken), I am going to close this.  @deeco if you find you're still seeing it, please feel free to re-open this issue.
