### ISSUE TITLE
Support container memory limits

### ISSUE THREAD

**Issue by mengesb** [test-kitchen/kitchen-dokken#167]
There's sometimes the need to support larger or smaller memory restrictions on testing containers. I see that kitchen-docker has that option [here](https://github.com/test-kitchen/kitchen-docker/blob/6075eb33dc245a8cd1bbd1f7a9bc72187bda40a9/lib/kitchen/driver/docker.rb#L343) and I've tried a a few syntax ways of specifying memory as an option however nothing seems to be doing the trick. Looking into [lib/kitchen/driver/dokken.rb](https://github.com/someara/kitchen-dokken/blob/131ce198d6764003a61825ff4be39f371820520d/lib/kitchen/driver/dokken.rb) I'm not quite sure where I'd add the option. Would it be simply adding `'Memory' => self[:memory],` to the config hash, or to the HostConfig hash within the config hash?

I'm happy to do the PR, but also amongst my attempts to test it looks like this would be a unit thing... so a pointer on where to add that if applicable would be great.

**Comment by mengesb** [comment]
I tried adding in

```
      default_config :memory, nil
```

to the dokken.rb file under the `class Dokken < Kitchen::Driver::Base` segment and inserting `'Memory' => self[:memory],` under both the config hash and the HostConfig segment of the config hash but I realized I didn't know of a good way to verify the results ... if you could point me in the right direction that'd be great.

**Comment by mengesb** [comment]
Seems that the docker driver can potentially take:
```yml
driver:
  name: docker
  customize:
    memory: 4096
    cpus: 2
```

or something to that effect. I'm not sure if I'm recalling correctly or not but does kitchen-dokken make use of the docker api the same way that kitchen-docker does? I've tried adding this using the dokken driver, while it didn't bail it didn't have any effect.

**Comment by rdubya16** [comment]
@mengesb Ever find a way to do this? Running into an issue where I need to increase memory as well.

**Comment by shanethehat** [comment]
The arguments passed to the Docker Engine API on container creation look to be defined here: https://github.com/test-kitchen/kitchen-dokken/blob/master/lib/kitchen/driver/dokken.rb#L290. Memory is not configured as part of the HostConfig settings, so it doesn't look like there's currently a way to inject a custom setting here.

**Comment by shanethehat** [comment]
FWIW in case anyone else comes to this - my issue was actually nothing to do with Dokken. It was Docker Desktop for OSX constraining the overall container memory. In figuring it out I did recreate the fix described above though.
