### ISSUE TITLE
chef-client cookbook no longer working with this driver

### ISSUE THREAD

**Issue by sam1el** [test-kitchen/kitchen-dokken#184]
As of the latest Chef-workstation release. The chef-client cookbook fails to run when using this drive. I have also tested with the vagrant and dokken drivers. It will work with the vagrant driver. Below is the error I see.

/opt/kitchen/cache/cookbooks/chef-client/recipes/service.rb:

30: systemd
31: upstart
32: windows
33: )
34:
35: init_style = node['chef_client']['init_style']
36:
37>> raise "The init style specified at node['chef_client']['init_style'] is not supported by the chef-client cookbook. Supported values are: #{supported_init_styles.join(',')}." unless supported_init_styles.include?(init_style)
38:
39: include_recipe "chef-client::#{init_style}_service"
40:

**Comment by bmhughes** [comment]
What OS and what is the `pid_one_command` option set to in the kitchen dokken config, I'm happily calling the chef-client cookbook with a variety of OSes without issue.

**Comment by sam1el** [comment]
Was on windows 10 no pid_one_command was set. Never was before and wasnt aware it was required

**Comment by marcparadise** [comment]
This seems verified working as of the most recent Workstation releases.  Please re-open this issue if you find this is occurring for you in  a current/future version.
