### ISSUE TITLE
Auto accept chef licenses 

### ISSUE THREAD

**Issue by gangadhar01a** [test-kitchen/kitchen-dokken#185]
We are using dokken provisioner along with latest chef dk (4.0.60), during the kitchen test it's required to accept the license. As we have automated the process, we do not except a user manually accept the license.

Does dokken provides a feature which auto accept the license and continue executing the kitchen tests?

For example: chef_zero has this ability to accept the license.

_"provisioner:
  name: chef_zero
  always_update_cookbooks: true
  log_level: info
  chef_license: accept-no-persist
  product_name: chef
  product_version: 14.10.9"_

**Comment by bbros-dev** [comment]
@gangadhar01a does this not work for you?:

```yaml
provisioner: 
  name: dokken
  chef_license: 'accept'
```
If not try adding `ENV CHEF_LICENSE=accept` to a Dockerfile.

If these do resolve the problem, this issue can be closed?

**Comment by Xorima** [comment]
Test-Kitchen recently got updated to pass in the `CHEF_LICENSE` environment variable.
