### ISSUE TITLE
provide docker_registory option

### ISSUE THREAD

**Issue by jaymzh** [test-kitchen/kitchen-dokken#217]
## :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

it is common to run a local dockerhub mirror to both not put too much load on dockerhub but also to avoid having to pay for increased limits. There is no way to prevent dokken from talking to dockerhub though. You can set `image`, `chef_image`, and `data_image` to `<host>/dokken/<whatever>`, `<host>/chef/chef`, and `<host>/dokken/kitchen-cache:latest`, but there's a bunch of intermediate images that all get pulled from dockerhub, breaking all of that.

It would be nice of there was a `docker_registry` config one could set to pull all images from there.

Specifically you end up with things like:

```
>>>>>>     Failed to complete #create action: [Couldn't find id: {"stream":"Step 1/13 : FROM centos:7"}
{"stream":"\n"}
{"errorDetail":{"message":"toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"},"error":"toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"}
] on base-ubuntu-1804
```

## Version

Test Kitchen version 2.5.0

## Environment

Ubuntu 18.04, using kitchen from Chef WS.

**Comment by jaymzh** [comment]
NOTE: I was able to work around this by pre-pulling `centos:7` from my mirror as part of `pre_create` lifecycle hook

**Comment by jaymzh** [comment]
Nope. Turns out that was not a work around, I just happened to be within my limit again. Sigh.

**Comment by tas50** [comment]
These are probably your friend: https://github.com/test-kitchen/kitchen-dokken/blob/master/lib/kitchen/driver/dokken.rb#L62

**Comment by tas50** [comment]
Also authoring to docker with https://github.com/test-kitchen/kitchen-dokken/pull/189 and getting a paid account

**Comment by jaymzh** [comment]
No I think you're misunderstanding. I have a mirror for a reason!! I don't want to not use it, I want to *use* it! And in fact I want kitchen-dokken to use it!

**Comment by jaymzh** [comment]
Actually those don't seem to even work @tas50 :

```
driver:
    name: dokken
    chef_version: 16.7.61
    chef_image: docker-dev.artifactory.vicarious.com/chef/chef
    privileged: true
    pull_platform_image: false
    pull_chef_image: false
```
Then I have a pre command to pull both images from local mirror, but it STILL tries to do SOMETHING with docker. No idea where that centos7 thing is coming from...

```
       Creating container chef-16.7.61
       Creating kitchen sandbox at /root/.dokken/kitchen_sandbox/42836eec50-base-ubuntu-1804
       Creating verifier sandbox at /root/.dokken/verifier_sandbox/42836eec50-base-ubuntu-1804

>>>>>> ------Exception-------

>>>>>> Class: Kitchen::ActionFailed

>>>>>> Message: 1 actions failed.

>>>>>>     Failed to complete #create action: [Couldn't find id: {"stream":"Step 1/13 : FROM centos:7"}

{"stream":"\n"}

{"errorDetail":{"message":"toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"},"error":"toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"}

] on base-ubuntu-1804
```

**Comment by jaymzh** [comment]
#thereifixedit =P
