### ISSUE TITLE
Oracle/CentOS 6 containers dont stay running

### ISSUE THREAD

**Issue by minsis** [test-kitchen/kitchen-dokken#224]
## :ghost: Brief Description

Oracle linux 6 and CentOS6 containers dont stay running after creation. You also can't just manually start it as it exits right away.

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #converge action: [Container 82f81a640debdcfdb334a06fd903306e27bdf8bcd396ae7af215857011968591 is not running
] on agent-oraclelinux-6
```

## Version

Not sure how to tell.

## Environment

Docker on WSL2. The cookbook is a simple installation of zabbix agent and the test is seeing if its installed

## Steps to Reproduce

My kitchen test has the following as the oraclelinux-6 config:
```yaml
- name: oraclelinux-6
    driver:
      image: dokken/oraclelinux-6
      privileged: true
      pid_one_command: /sbin/init
```

I tried this with and without the pid_one_command and get the same results. This is also happening on CentOs6 container.

## Expected Result

Container to continue running for the kitchen test.

## Actual Result

As soon as the container is built it immediately stops running and the test cannot continue

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.

**Comment by marcparadise** [comment]
@minsis could you provide the full output of your `kitchen` run, and the log file?

**Comment by minsis** [comment]
Sorry I've forgotten about this issue.

From what I do remember this was an environment issue with WSL2. For some reason WSL2 can't run the older non-systemd containers.

I can still provide logs and such if you want when I get some time.

**Comment by tas50** [comment]
Closing this one out since CentOS 6 is about 3 years EOl at this point
