### ISSUE TITLE
View Chef logs live and colorized?

### ISSUE THREAD

**Issue by evandam** [test-kitchen/kitchen-dokken#236]
## :frowning_person: Problem Statement

Logs during the Chef run are not visible until the run is complete, and color is lost. The logs pause at `Preparing client.rb`, and then all logs get flushed.

## :grey_question: Possible Solution

An option to provide in kitchen.yml to immediately flush logs as they are received and to preserve color (ex: if running kitchen manually, not in CI).

## :arrow_heading_up: Describe alternatives you've considered

Leave things the way they are :innocent:

I've tried things like `chef_options: " -z --color"` but no luck.

## :heavy_plus_sign: Additional context
Thanks folks!

**Comment by YAMLcase** [comment]
#5 related, but reverted to newline issues

**Comment by collinmcneese** [comment]
Hey @evandam  👋🏻  -- color output is supported now and merged in with #250, is this good to close out?

**Comment by evandam** [comment]
Sounds good, thanks @collinmcneese
