### ISSUE TITLE
README blog URL redirects

### ISSUE THREAD

**Issue by ashemedai** [test-kitchen/kitchen-dokken#273]
## Brief Description

The blog URL in the README redirects to the frontpage.

## Version

N/A

## Environment

N/A

## Scenario

Reading the mentioned blog post.

## Steps to Reproduce

Scroll down in the README, notice blog post, try to click and read.

## Expected Result

Be able to read the blog post.

## Actual Result

Get redirected to the main website.

## :heavy_plus_sign: Additional context

Link can be replaced with https://www.chef.io/blog/kitchen-docker-or-kitchen-dokken-using-test-kitchen-and-docker-for-fast-cookbook-testing

**Comment by tas50** [comment]
Link checking added in https://github.com/test-kitchen/kitchen-dokken/pull/291
