### ISSUE TITLE
converge doesn't exit with proper exit code

### ISSUE THREAD

**Issue by Stromweld** [test-kitchen/kitchen-dokken#318]
Using latest versions of kitchen-dokken and test-kitchen when running a converge if the chef-client fails convergence due to an error kitchen converge exits with 0 exit code indicating a success.

**Comment by Stromweld** [comment]
I was able to narrow down the issue this block https://github.com/test-kitchen/kitchen-dokken/blob/main/lib/kitchen/provisioner/dokken.rb#L76

When I comment out the ensure after rescue the client exits with the correct exit code. But with the ensure the clean sandbox method is called and updates @exit_code leaving a 0 exit_code from the transporter.

**Comment by damacus** [comment]
@Stromweld do you think #319 fixed this?

**Comment by Stromweld** [comment]
yes it is working now.
