### ISSUE TITLE
Allow use of profile_ruby in the dokken provisioner

### ISSUE THREAD

**Issue by chilicheech** [test-kitchen/kitchen-dokken#34]
Please allow the use of profile_ruby in the dokken provisioner as described here: http://martinb3.io/profiling-chef-client-12-6/
The yaml would look like this:

```
provisioner:
  name: dokken
  profile_ruby: true
```

This would essentially add the `--profile-ruby` option to the chef-client command in here:
https://github.com/someara/kitchen-dokken/blob/170888b493c39e766f96c10d809cb7234c7a2510/lib/kitchen/provisioner/dokken.rb#L52

Cheers,

**Comment by someara** [comment]
added here 3a15ebc393769309bc25f5c39ae4ffb016969eb9
released as 1.0.2

**Comment by someara** [comment]
Sorry.. I didn't quite test that enough. Reverting for now. Will try again.
-s

**Comment by tas50** [comment]
This is merged to master now to match the chef-zero provisioner
