### ISSUE TITLE
Need to populate a fake run_list if using policyfile

### ISSUE THREAD

**Issue by mattstratton** [test-kitchen/kitchen-dokken#56]
When I try to use dokken to test a cookbook created with Policyfile, it complains because there is no run_list set.

I am able to work around this by setting a run_list under the suite, which is ignored, and everything then works fine, but it would be great if dokken could detect this is a policyfile and then not check for the run_list.

**Comment by Xorima** [comment]
Hi, 

I am doing a cleanup of issues, if this is still an issue please re-open

Thanks

Jason
